FROM python:3.9.25-alpine3.22 AS builder

WORKDIR /app

RUN apk add --no-cache build-base linux-headers pcre-dev

COPY requirements.txt .
RUN pip3.9 install --prefix=/install -r requirements.txt

FROM python:3.9.25-alpine3.22

WORKDIR /app
EXPOSE 8080

RUN apk add --no-cache pcre

COPY --from=builder /install /usr/local
COPY payment.ini *.py requirements.txt ./

CMD ["uwsgi", "--ini", "payment.ini"]