services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: dockerfile
    image: mongodb:1.0
    container_name: mongodb
  user:
    build: 
      context: ./user
      dockerfile: dockerfile
    image: user:1.0
    container_name: user
    depends_on: redis mongodb
  catalogue:
    build:
      context: ./catalogue
      dockerfile: dockerfile
    image: catalogue:1.0
    container_name: catalogue
    depends_on:
      - mongodb

networks:
  default:
    name: roboshop

