FROM node:20
RUN mkdir /app
WORKDIR /app
COPY package.json .
RUN npm install
COPY server.js .
ENV REDIS="true" \
    REDIS_URL="redis://redis:6379/catalogue" \
    CATALOGUE="true" \
    CATALOGUE_URL="http://catalogue:8080"
CMD ["node", "server.js"]