FROM node:20-alpine
RUN mkdir /app
WORKDIR /app
COPY package.json .
RUN npm install
COPY server.js .
ENV REDIS="true" \
    REDIS_HOST="redis" \
    CATALOGUE_HOST="catalogue" 
CMD ["node", "server.js"]