# FROM node:20-alpine
# RUN mkdir /app
# WORKDIR /app
# COPY package.json .
# RUN npm install
# COPY server.js .
# ENV REDIS="true" \
#     REDIS_HOST="redis" \
#     CATALOGUE_HOST="catalogue" 
# CMD ["node", "server.js"]

FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json .
COPY *.JS .
RUN npm install
RUN npm install 

FROM node:20-alpine
WORKDIR /app
EXPOSE 8080
COPY --from=builder /app .
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
USER roboshop
CMD ["server.js"]
ENTRYPOINT ["node"]