FROM maven:3.9.14
EXPOSE 8080
RUN mkdir /app
WORKDIR /app
COPY src .
COPY pom.xml .

RUN mvn clean package
RUN mv target/shipping-1.0.jar shipping.jar

ENV CART_ENDPOINT=cart:8080 \
    DB_HOST=mysql

CMD ["java", "-jar", "shipping.jar"]