FROM node:20.20.2-alpine3.23
RUN mkdir /app
WORKDIR /app
COPY package.json .
COPY server.js .
RUN npm install
ENV MONGO="true" \
    MONG0_URL="mongodb://mongodb:27017/catalogue"
CMD ["node", "server.js"]