FROM node:20
RUN mkdir /app
WORKDIR /app
COPY package.json .
RUN npm install
COPY server.js .
ENV REDIS="true" \
    REDIS_URL="redis://redis:6379/catalogue" \
    MONGO="true" \
    MONGO_URL="mongodb://mongodb:27017/user"
CMD ["node", "server.js"]