FROM node:20
RUN mkdir /app
WORKDIR /app
COPY package.json .
COPY server.js .
RUN npm install
ENV REDIS="true" \
    REDIS_HOST="redis" \
    MONGO="true" \
    MONGO_HOST="mongodb"
CMD ["node", "server.js"]